export const THEME = {
    MAIN_BG: '#F1F3F2',
    MAIN_FONT_COLOR: '#1B1F20',
    SECONDARY_FONT_COLOR: '#C7CAC9',
    WHITE_BG: '#FEFEFE',
    POST_FONT_COLOR: '#696B6F',
    TITLE_FONT_COLOR: '#EEFDFF',
    WHITE_FONT_COLOR: '#FAFCFC',
    POST_BG_COLOR: '#F6F8FA',
    DELETE_POST_BTN: '#F10602',
    ADD_POST_BTN: '#1F5DE1'
}